server:
  port: 8081

spring:
  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/fotodetector
    username: postgres
    password: U2110235

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  file:
    name: LOG
    max-size: 1MB
    max-history: 10

  app:
    image:
      bucket: /Users/azimo/OneDrive/??????? ????/fotodetector/images

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
      enabled: true

openai:
  api:
    key: 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

